### ISSUE TITLE
Making shared folders/mounts in S3 read-only

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#164]
Having S3 mounts in workspaces seems to be a good idea for sharing tutorial notebooks as demonstrated by @echyam and @abarciauskas-bgse tutorials. Is there a way to make some folders read-only? My private and shared folders should be read-write for me, but my shared folder should be read-only for everyone else.

**Comment by abarciauskas-bgse** [comment]
What if we create an image that includes the example notebooks we are generating (i.e. "MAAP Plus Examples")? And then users can create workspaces from that image and corresponding stack?

**Comment by echyam** [comment]
I experimented with mounting separate ADE directories to different levels of s3 bucket prefixes.  
We can do something like:
`s3://maap-dev-dataset/maap-users` -> `/projects/maap-users` (read-only)
`s3://maap-dev-dataset/maap-users/eyam` -> `/projects/eyam` (read-write)

I can touch a file in under `/projects/eyam` that will sync and show up under `/projects/maap-users/eyam`.
i.e. I can open and write a file `/projects/eyam/foo.txt`.  I can access the same file also as `/projects/maap-users/eyam/foo.txt`, but that version will not allow me to save any updates.

The nice part is if the shared file is a notebook, say `/projects/maap-users/eyam/sine-result0.ipynb`, I can still edit run notebook when run from a read-only path; writing any updated cells or outputs from that notebook to a relative path will still be blocked.

A caveat would be that if I am still making changes to  `/projects/eyam/foo.txt`, but you already have  `/projects/maap-users/eyam/foo.txt` open, the read-only copy you opened will be cached, and you'd have to close it and re-open to see any updates when I make a new save.  This happens regardless of whether you have read-write permissions to the file.

What do you think @gchang @abarciauskas-bgse ?

**Comment by echyam** [comment]
@abarciauskas-bgse That's a great idea!  I already started working on making ADE Tutorial Notebooks (#151), which are pushed to https://repo.nasa.maap.xyz/maap-devs/maap-tutorials.

The plan is that after reviewing the tutorial notebooks, we will pre-package the ADEs with these under the workspace home directory.

These are currently just showing the user how to do everything from within the ADE.  I would love to add notebooks that follow a user story and go from a more complex python script with outputs to a registered algorithm.

**Comment by abarciauskas-bgse** [comment]
@echyam just to make sure I understand - is the read/write for `/projects/eyam/foo.txt` only for the `eyam` user or for all users?

What makes sense to me (and what I think is what you are suggesting is possible) is that, given I am working in a shared workspace, I can read/write everything under `/projects/aimeeb/` and everyone the workspace is shared with can read those files but not write to them. They could copy anything I have in there to their respective `/projects/username/` and then make changes.

**Comment by echyam** [comment]
@abarciauskas-bgse `/projects/username` is mounted as read-write for everyone who has access to the workspace, but only gets added if a user opens it.  `/projects/maap-users/username` is read-only for everyone in every workspace.

Let's say I create a new workspace:
1. I open it as `eyam`:
- `s3://maap-dev-dataset/maap-users` -> `/projects/maap-users` will get mounted as read-only
- `s3://maap-dev-dataset/maap-users/eyam` -> `/projects/eyam` will get mounted as read-write
2. I share the workspace with you as `aimeeb`:
- Nothing changes
3. You open the workspace as `aimeeb`:
- `s3://maap-dev-dataset/maap-users/aimeeb` -> `/projects/aimeeb` will get mounted as read-write
- You will also get read-write access to `/projects/eyam` and I will gain read-write access to `/projects/aimeeb`
- `/projects/maap-users` is still read-only for both of us

**Comment by echyam** [comment]
The benefit of mounting `s3://maap-dev-dataset/maap-users` -> `/projects/maap-users` as read-only is we wouldn't have to share a workspace (and expose write access) anymore.  You could grab a read-only copy of my `/projects/eyam/foo.txt` under `/projects/maap-users/eyam/foo.txt` without me sharing any workspace.

**Comment by abarciauskas-bgse** [comment]
That sounds reasonable to me @echyam perhaps it makes sense to share this functionality with the UWG through some documentation + demo and see what they think.

**Comment by oddes** [comment]
This issue is blocked by https://app.zenhub.com/workspaces/maap-platform-5ee7f0d1f440de0024cd359b/issues/maap-project/zenhub/188

**Comment by echyam** [comment]
11/10: modified s3 mount validity using `df -h | grep s3fs` command instead of getting Che orgs to be independent of issue #188

**Comment by echyam** [comment]
updated `s3://maap-dev-dataset/maap-users` -> `/projects/maap-users` will get mounted as read-only

**Comment by echyam** [comment]
@oddes  I modified s3 mount validity check using `df -h | grep s3fs` command instead of getting Che orgs to be independent of issue #188

error messaging should work now

**Comment by oddes** [comment]
@echyam 
Verified but still not loading the maap-users folder. Looks like still the Che orgs error, needs to be fixed.

**Comment by gchang** [comment]
In the dev environment, it seems like most accounts have been removed from the maap-users organization so this would not work. However, once I was added to the maap-users organization, this works.
