### ISSUE TITLE
MAAP Account Status not updating with status change

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#537]
As Sri pointed out below, it appears that a user's account status isn't updating in their profile if an admin changes their status within the syncope profile.  I suspect that this is because this status information is set in a session variable upon login and isn't being updated after the status change. It's also worth noting that this has implications on ADE access as well, which Sri also observed was accessible to users with a status of "suspended".

_Originally posted by @oddes in https://github.com/MAAP-Project/ZenHub/issues/479#issuecomment-1111629131_

>Also, status is not in sync with Profile: 
><img width="1209" alt="Screen Shot 2022-04-27 at 6 07 46 PM" src="https://user-images.githubusercontent.com/34038615/165656241-3f6b23d0-960d-4338-8e40-614d991b9075.png">

**Comment by anilnatha** [comment]
With the recent set of updates made to the MAAP API and some additional updates needed in the Portal, this issue should be able to be resolved by making on demand calls to the API to fetch a user's account information rather than fetching it from the session.

**Comment by anilnatha** [comment]
I've resolved this issue by using the information that is already being fetched by the profile page to fetch key information.

However, we need to make one more update to our member model (#553) so that I can close out this ticket.

**Comment by anilnatha** [comment]
@oddes This issue has been fixed and is ready to be tested in UAT.  You can use the new MAAP User's Admin page (#547) to test this by toggling a user's status.

**Comment by oddes** [comment]
@anilnatha 
1. I have updated the status to "Suspended"
2. I have logged in again and I still see the status as "ACTIVE", it supposed to be "Suspended".
